# Site
repository: jamalavedra/jamalavedra.github.io
favicon: images/favicon.ico

# Personal info
name: Jaume Alavedra Mas
title: Software developer
email: jamalavedra@gmail.com
website: blog.jamalavedra.me

# Social links
twitter_username: jamalavedra
github_username: jamalavedra
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jamalavedra
linkedin_username: jaume-alavedra
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Biography
about_profile_image: images/me.jpeg
about_content: | # this will include new lines to allow paragraphs
  I'm a software engineer with a background in security and in web development. I'm currently working at Onsite.fun, Working to make remote work more human by building.

  I also have experience in novel Computer Vision techniques, particularly in deep feature extraction and detection.

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me

#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
